name       : openshot-qt
version    : 2.4.1
release    : 4
source     :
    - https://github.com/OpenShot/openshot-qt/archive/v2.4.1.tar.gz : da388c08cd94ec503a57756871244d9bb8746973807e2f95618a0d9d5e11fae9
license    : GPL-3.0
component  : multimedia.video
summary    : Openshot video editor
description: |
    OpenShot Video Editor is a free, open-source, non-linear video editor. It can create and edit videos and movies using many popular video, audio, and image formats. Create videos for YouTube, Flickr, Vimeo, Metacafe, Xbox, and many more common formats!
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - libopenshot
    - python-httplib2
    - python-pyzmq
    - python3-qt5
    - python3-sip
    - pyxdg
    - qt5-svg
    - qt5-webkit
    - sdl1-image
build      : |
    %python3_setup
install    : |
    %python3_install
