name       : openshot-qt
version    : 2.4.2
release    : 7
source     :
    - https://github.com/OpenShot/openshot-qt/archive/v2.4.2.tar.gz : 957792cb5c07ec7c593b9af7d234f75110ac8df0aa179e284ed84f48f552d9bd
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : Openshot video editor
description: |
    OpenShot Video Editor is a free, open-source, non-linear video editor. It can create and edit videos and movies using many popular video, audio, and image formats. Create videos for YouTube, Flickr, Vimeo, Metacafe, Xbox, and many more common formats!
builddeps  :
    - pkgconfig(python3)
    - python-setuptools
rundeps    :
    - libopenshot
    - python-httplib2
    - python-pyzmq
    - python3-qt5
    - python3-sip
    - pyxdg
    - qt5-svg
    - qt5-webkit
    - sdl1-image
build      : |
    %python3_setup
install    : |
    %python3_install
