name       : openshot-qt
version    : 2.5.0
release    : 11
source     :
    - https://github.com/OpenShot/openshot-qt/archive/v2.5.0.tar.gz : b48d2d924d9124a61d5053b2c04b2f083f16fd86395f0e0f231082d34ff0521f
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : Openshot video editor
description: |
    OpenShot Video Editor is a free, open-source, non-linear video editor. It can create and edit videos and movies using many popular video, audio, and image formats. Create videos for YouTube, Flickr, Vimeo, Metacafe, Xbox, and many more common formats!
builddeps  :
    - pkgconfig(python3)
    - python3-qt5
rundeps    :
    - libopenshot
    - python-httplib2
    - python-pyzmq
    - python3-qt5
    - python3-sip
    - pyxdg
    - qt5-svg
    - qt5-webkit
    - sdl1-image
build      : |
    %python3_setup
install    : |
    %python3_install
