name       : openshot-qt
version    : 2.5.1
release    : 14
source     :
    - https://github.com/OpenShot/openshot-qt/archive/v2.5.1.tar.gz : 4c25eb9a5de42e749de4c6ca2f7a313c60e1283fe52d70c121629dbb8bb2df7b
homepage   : https://www.openshot.org/
license    : GPL-3.0-or-later
component  : multimedia.video
summary    : Openshot video editor
description: |
    OpenShot Video Editor is a free, open-source, non-linear video editor. It can create and edit videos and movies using many popular video, audio, and image formats. Create videos for YouTube, Flickr, Vimeo, Metacafe, Xbox, and many more common formats!
builddeps  :
    - pkgconfig(python3)
    - python3-qt5
rundeps    :
    - libopenshot
    - python-httplib2
    - python-pyzmq
    - python3-qt5
    - pyxdg
    - sdl1-image
build      : |
    %python3_setup
install    : |
    %python3_install
